# Generated by Django 4.2 on 2023-04-20 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_gems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
    ]
