# Generated by Django 4.2 on 2023-04-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_client_gems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.item')),
            ],
        ),
        migrations.DeleteModel(
            name='StoneCustomer',
        ),
    ]
