# Generated by Django 4.2 on 2023-04-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_itemcustomer_delete_stonecustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='stone',
            new_name='item',
        ),
    ]
